### ISSUE TITLE
Problem: Sum of Two

### ISSUE THREAD

**Issue by ajayg415** [ajayg415/Javascript-Algorithms#12]
Given an array of integers, return indices of the two numbers such that they add up to a specific target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

**Example:**
```js
Given nums = [2, 7, 11, 15], target = 9,

Because nums[0] + nums[1] = 2 + 7 = 9,
return [0, 1].

var twoSum = function(nums, target){
  //Code goes here
}
```

**Comment by ajayg415** [comment]
@krishna63, @msreddy09, @pradeeptinku : Any comments

```js
var twoSum = function(nums, target) {
  for(let i=0;i<nums.length;i++){
    let arrCopy = nums.slice();
    arrCopy[i] = null;
    const num = target-nums[i]
    if(arrCopy.includes(num)){
      return [i, arrCopy.indexOf(num)]
    }
  }
};
```

**Comment by krishna63** [comment]
@ajayg415 : The logic LGTM.

**_Note:_** `includes` does not work in IE, so possible while writing such kind of logic's it is better to write with methods compatible for all the browsers.

**Comment by msreddy09** [comment]
The logic picks only the first matched two indices. 
an example is here.

twoSum([1,2,4,3,6,-1], 5)

returns only  [0,2]

but [1,3], [4,5] is also possible pair.

**Comment by ajayg415** [comment]
@msreddy09 The question says `You may assume that each input would have exactly one solution, and you may not use the same element twice.` so we can assume the solution which I suggest works properly in this case. But, what  you're saying is correct, but we should consider it for another problem statement.

**Comment by ajayg415** [comment]
@krishna63 @msreddy09 

I found below similar solution using `Javascript Sets()`. Have a look, its interesting. 

```js
const findSum = (arr, val) => {
  let searchValues = new Set();
  searchValues.add(val - arr[0]);
  for (let i = 1, length = arr.length; i < length; i++) {
    let searchVal = val - arr[i];
    if (searchValues.has(arr[i])) {
      return true;
    } else {
      searchValues.add(searchVal);
    }
  };
  return false;
};
```

**Comment by msreddy09** [comment]
In that case why not this?
var twoSum = function(nums, target) {
  
  for(let i=0;i<nums.length;i++){   
    const num = target-nums[i]
    if(nums.includes(num)){
      return [i, nums.indexOf(num)]
    }
  }
}

**Comment by ajayg415** [comment]
@msreddy09, Logic is similar with less coding, I'm good with this.

**Comment by ajayg415** [comment]
Merged solution with master branch. https://github.com/ajayg415/Javascript-Algorithms/commit/00aa93173f8266984d7f607248e4de2d6d2fc944
