### ISSUE TITLE
Problem: Non-Constructible Change

### ISSUE THREAD

**Issue by ajayg415** [ajayg415/Javascript-Algorithms#19]
Given an array of positive integers representing the values of coins in your possession, write a function that returns the minimum amount of change (the minimum sum of money) that you **cannot**  create. The given coins can have any positive integer value and aren't necessarily unique (i.e., you can have multiple coins of the same value).

  For example, if you're given `coins = [1, 2, 5]`, the minimum amount of change that you can't create is `4`. If you're given no
  coins, the minimum amount of change that you can't create is '1'

> _Note: O(nlogn) time | O(1) space - where n is the number of coins_

```js
Sample Input: 
Coins:  = [5, 7, 1, 1, 2, 3, 22]
Sample Output: 20
```

```js
function nonConstructibleChange(coins) {
  // Write your code here.
  return 1;
}
```

**Comment by ajayg415** [comment]
```js
function nonConstructibleChange(coins) {
  coins.sort((a,b) => (a-b))
  let storedVal = 0
  for(const coin of coins){
    if( coin > storedVal +1) return storedVal + 1;
      storedVal += coin;
    }
  return storedVal+1
}
```

@krishna63 , @msreddy09 How about this solution?

**Comment by msreddy09** [comment]
I would like to see more examples for every problem. Don't mind, I did not get the problem most of the time.

**Comment by ajayg415** [comment]
@msreddy09, my mistake I didn't add the question completely.

**Comment by ajayg415** [comment]
Code merged with master branch: https://github.com/ajayg415/Javascript-Algorithms/pull/29
